<?php

/******************************************************************************
 *
 *	PROJECT: Flynax Classifieds Software
 *	VERSION: 4.9.1
 *	LISENSE: FL0F971OQTZ9 - https://www.flynax.com/flynax-software-eula.html
 *	PRODUCT: Classified Ads Script
 *	DOMAIN : gmowin.com
 *	FILE   : TOKEN.PHP
 *
 *	This script is a commercial software and any kind of using it must be
 *	coordinate with Flynax Owners Team and be agree to Flynax License Agreement
 *
 *	This block may not be removed from this file or any other files with out
 *	permission of Flynax respective owners.
 *
 *	Copyrights Flynax Classifieds Software | 2022
 *	https://www.flynax.com
 *
 ******************************************************************************/

namespace Flynax\Plugin\WordPressBridge\WordPressAPI;

use Flynax\Plugin\WordPressBridge\Response;

class Token
{
    /**
     * Token of the Flynax bridge plugin
     */
    const FLB_WP_TOKEN_KEY = 'flb_wp_token';

    /**
     * Token of the WordPress bridge plugin
     */
    const FLB_FL_TOKEN_KEY = 'flb_fl_token';

    /**
     * @var \rlConfig
     */
    private $rlConfig;

    /**
     * @var \rlDb
     */
    private $rlDb;

    /**
     * @var \rlActions
     */
    private $rlActions;

    /**
     * Token constructor.
     */
    public function __construct()
    {
        if (!$GLOBALS['rlConfig']) {
            $GLOBALS['reefless']->loadClass('Config');
        }

        $this->rlConfig = $GLOBALS['rlConfig'];
        $this->rlDb = $GLOBALS['rlDb'];
        $this->rlActions = wbMake('rlActions');
    }

    /**
     * Save Flynax Bridge plugin token to the Flynax config table
     *
     * @param string $token - Generated token
     *
     * @return bool
     */
    public function saveWpToken($token)
    {
        if (!$token) {
            return false;
        }

        return $this->rlConfig->setConfig(self::FLB_WP_TOKEN_KEY, $token);
    }

    /**
     * Save WordPress bridge plugin token to the Flynax config table
     *
     * @param string $token - Generated token
     *
     * @return bool
     */
    public function saveFlToken($token)
    {
        if (!$token) {
            return false;
        }

        return $this->rlConfig->setConfig(self::FLB_FL_TOKEN_KEY, $token);
    }

    /**
     * Generate WordPress bridge plugin token
     *
     * @param int $length - Length of the token
     *
     * @return string
     * @throws \Exception
     */
    public function generateFlToken($length = 32)
    {
        return bin2hex(random_bytes($length));
    }

    /**
     * Get token, which is generated by Flynax Bridge plugin
     *
     * @return string
     */
    public function getWpToken()
    {
        return (string) $this->rlDb->getOne('Default', sprintf("`Key` = '%s'", self::FLB_WP_TOKEN_KEY), 'config');
    }

    /**
     * Get token, which is generated by WordPress bridge plugin
     *
     * @return string
     */
    public function getFlToken()
    {
        return (string) $this->rlDb->getOne('Default', sprintf("`Key` = '%s'", self::FLB_FL_TOKEN_KEY), 'config');
    }

    /**
     * Clear all Generated token from the config table
     */
    public function clearAllTokens()
    {
        $tokens = array(self::FLB_FL_TOKEN_KEY, self::FLB_WP_TOKEN_KEY);

        foreach ($tokens as $token) {
            $this->rlConfig->setConfig($token, '');
        }

        Response::success('Tokens has been successfully removed', 200);
    }
}
